dataswap/dataswapjs

README.md
package.json

chore: Unified command style

---

src/shared/types/evmEngineType.ts

feat: Add EvmEx class to include constructor EvmEngine

---

test/fixtures.ts
test/shared/error.ts
test/testkits/module/datasets/DatasetsMetadataTestKit.ts
test/unittests/module/datasets.test.ts

check and update the specification of comments and file headers.(test directory)
✅ Closes: #41

style: 💄 check the comments and file headers

---

src/core/carstore/types/index.ts
src/core/escrow/types/index.ts
src/index.ts
src/message/repo/datastore/index.ts
src/message/repo/datastore/model/index.ts
src/message/types/index.ts
src/module/dataset/challenge/types/index.ts
src/module/dataset/metadata/types/index.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/dataset/requirement/repo/evm/index.ts
src/module/dataset/requirement/types/index.ts
src/module/matching/bids/repo/evm/index.ts
src/module/matching/bids/types/index.ts
src/module/matching/metadata/repo/evm/index.ts
src/module/matching/metadata/types/index.ts
src/module/matching/target/repo/evm/index.ts
src/module/matching/target/types/index.ts
src/shared/operate/types/index.ts
src/shared/state/types/index.ts
src/shared/types/carstoreType.ts
src/shared/types/dataType.ts
src/shared/types/datasetDraft.ts
src/shared/types/datasetType.ts
src/shared/types/escrowType.ts
src/shared/types/evmEngineType.ts
src/shared/types/filecoinType.ts
src/shared/types/matchingDraft.ts
src/shared/types/matchingType.ts

chore: 🤖 Check and update the specification of comments

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/labels.yml
.github/pull_request_template.md
.github/workflows/label-syncer.yml

1.Submit issues and PR template
2.Sync Labels
✅ Closes: #51

feat: 🎸 add issues and PR specifications

---

.github/workflows/test.yml

chore: 🤖 Remove sleep time from test workflow

---

test/helpers/module/datasetsHelper.ts
test/interfaces/helper/module/IDatasetshelper.ts
test/interfaces/setup/IGenerator.ts
test/shared/utils.ts
test/testkits/setup/generator.ts

For workflows where valid test data is unnecessary, use generated fake data
✅ Closes: #24
close

feat: 🎸 auto generate proofs

---

package-lock.json
package.json
src/message/repo/datastore/index.ts
src/message/repo/datastore/model/index.ts
src/message/types/index.ts
test/unittests/datastore/message.test.ts

feat: 🎸 add unimessage datstore

---

LICENSE
README.md
templates/readme.md

docs: ✏️ Unified Document Style README

---

.mocharc.json
test/assertions/module/datasetsAssertion.ts
test/helpers/module/datasetsHelper.ts
test/interfaces/helper/module/IDatasetshelper.ts
test/interfaces/setup/IGenerator.ts
test/testkits/module/datasets/DatasetsMetadataTestKit.ts
test/testkits/module/datasets/DatasetsProofTestKit.ts
test/testkits/module/datasets/DatasetsRequirementTestKit.ts
test/testkits/setup/generator.ts
test/unittests/module/datasets.test.ts
test/unittests/module/datasetsChallenge.test.ts
test/unittests/module/datasetsProof.test.ts
test/unittests/module/datasetsRequirement.test.ts

feat: 🎸 add test code for datasets

---

test/assertions/module/datasetsAssertion.ts
test/testkits/module/datasets/DatasetsRequirementTestKit.ts
test/unittests/module/datasetsRequirement.test.ts

feat: 🎸 add test code for datasetsrequirement

---

.vscode/launch.json
src/core/carstore/repo/evm/index.ts
test/assertions/core/carstoreAssertion.ts
test/interfaces/assertions/core/ICarstoreAssertion.ts
test/unittests/core/carstore.test.ts

test: 💍 Add carstore test code

---

src/module/dataset/challenge/types/index.ts
test/assertions/module/datasetsAssertion.ts
test/testkits/abstract/TestBase.ts
test/unittests/module/datasetsChallenge.test.ts

feat: 🎸 add test code for datasetschallengeproof

---

package-lock.json
package.json

feat: 🎸 upgrade filecoin version ->1.5

---

package-lock.json
package.json

fix: 🐛 update net->v2.5.1

---

src/index.ts

feat: 🎸 export feature for debug

---

.github/workflows/test.yml
package-lock.json
package.json
src/module/dataset/challenge/types/index.ts
src/module/matching/target/repo/evm/index.ts
src/module/matching/target/types/index.ts
test/assertions/module/datasetsAssertion.ts
test/assertions/module/matchingsAssertion.ts
test/fixtures.ts
test/helpers/module/matchingsHelper.ts
test/interfaces/helper/module/IMatchingsHelper.ts
test/interfaces/setup/IGenerator.ts
test/testkits/module/matchings/MatchingsTestKit.ts
test/testkits/module/matchings/abstract/MatchingsTestBase.ts
test/testkits/setup/generator.ts
test/unittests/module/matchings.test.ts

feat: 🎸 add test code for matchings

---

src/shared/types/evmEngineType.ts
test/assertions/module/matchingsAssertion.ts
test/helpers/module/matchingsHelper.ts
test/interfaces/assertions/module/IMatchingsAssertion.ts
test/testkits/module/matchings/MatchingsBidsTestKit.ts
test/testkits/module/matchings/MatchingsTargetTestKit.ts
test/testkits/setup/generator.ts
test/unittests/module/matchings.test.ts

feat: 🎸 add test code for matchingsbids

---

src/core/escrow/repo/evm/index.ts
src/shared/types/escrowType.ts
test/shared/utils.ts
test/unittests/decode/escrow.test.ts

test: 💍 Add escrow decode msg test

---

test/testkits/abstract/TestBase.ts
test/testkits/module/datasets/DatasetsMetadataTestKit.ts
test/testkits/module/datasets/DatasetsProofTestKit.ts
test/testkits/setup/contractsManager.ts
test/testkits/setup/generator.ts
test/unittests/module/datasets.test.ts
test/unittests/module/datasetsChallenge.test.ts
test/unittests/module/datasetsProof.test.ts
test/unittests/module/datasetsRequirement.test.ts

refactor: 💡 Standardize dataset and matching-related test code

---

test/unittests/decode/escrow.test.ts

fix: 🐛 Escrow decode params comparison expression

---

src/module/datacaps/repo/evm/index.ts
test/assertions/module/datacapsAssertion.ts
test/helpers/module/matchingsHelper.ts
test/interfaces/assertions/module/IDatacapsAssertion.ts
test/interfaces/setup/IGenerator.ts
test/testkits/setup/contractsManager.ts
test/testkits/setup/generator.ts
test/unittests/module/datacaps.test.ts

test: 💍 Add datacaps test code

---

src/core/filplus/repo/evm/index.ts
src/index.ts
src/module/dataset/requirement/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/model.ts
src/module/dataset/requirement/repo/evm/index.ts
src/module/dataset/requirement/types/index.ts
src/shared/types/datasetType.ts
test/assertions/core/filplusAssertion.ts
test/assertions/module/datasetsAssertion.ts
test/interfaces/assertions/core/IFilplusAssertion.ts
test/interfaces/assertions/module/IDatasetsAssertion.ts
test/interfaces/setup/IGenerator.ts
test/shared/utils.ts
test/testkits/setup/generator.ts
test/unittests/core/filplus.test.ts
test/unittests/datastore/datasetrequirements.test.ts
test/unittests/decode/datasetrequirement.test.ts

feat: 🎸 add decode for datasets requirement

---

test/assertions/module/storagesAssertion.ts
test/unittests/module/storages.test.ts

test: 💍 Add storages test code

---

src/core/escrow/repo/datastore/index.ts
src/core/escrow/repo/datastore/model.ts
src/core/escrow/repo/evm/index.ts
src/core/escrow/types/index.ts
test/unittests/datastore/escrow.test.ts
test/unittests/decode/escrow.test.ts

feat: 🎸 Add escrow datastore function

---

src/core/filecoin/repo/evm/index.ts
test/assertions/core/filecoinAssertion.ts
test/unittests/core/filecoin.test.ts

test: 💍 Add filecoin test code

---

src/module/datacaps/repo/evm/index.ts
test/unittests/decode/datacaps.test.ts

test: 💍 Add datacaps decode message code

---

src/module/matching/metadata/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/model.ts
src/module/matching/metadata/repo/evm/index.ts
src/module/matching/metadata/types/index.ts
test/assertions/module/matchingsAssertion.ts
test/helpers/module/matchingsHelper.ts
test/interfaces/assertions/module/IMatchingsAssertion.ts
test/interfaces/setup/IGenerator.ts
test/testkits/module/matchings/MatchingsTestKit.ts
test/testkits/setup/generator.ts
test/unittests/datastore/matchingmetadata.test.ts
test/unittests/decode/matchingmetadata.test.ts
test/unittests/module/matchings.test.ts

feat: 🎸 add decode for matchings metadata

---

src/module/matching/target/repo/datastore/index.ts
src/module/matching/target/repo/datastore/model.ts
src/module/matching/target/repo/evm/index.ts
src/module/matching/target/types/index.ts
test/assertions/module/matchingsAssertion.ts
test/helpers/module/matchingsHelper.ts
test/interfaces/assertions/module/IMatchingsAssertion.ts
test/testkits/module/matchings/MatchingsTargetTestKit.ts
test/unittests/datastore/matchingtarget.test.ts
test/unittests/decode/matchingtarget.test.ts

feat: 🎸 add decode for matchings target

---

test/unittests/decode/filplus.test.ts

test: 💍 Add filplus decode message code

---

src/module/matching/bids/repo/evm/index.ts
test/unittests/decode/matchingbids.test.ts

feat: 🎸 add decode for matching bids

---

src/core/roles/repo/evm/index.ts
test/unittests/decode/roles.test.ts

test: 💍 Add roles decode message code

---

src/module/dataset/metadata/repo/evm/index.ts
src/module/matching/metadata/repo/evm/index.ts
test/unittests/decode/datasetmetadata.test.ts
test/unittests/decode/matchingmetadata.test.ts

fix: 🐛 Correct parsing issues with datasetId and matchingId

---

package-lock.json
package.json
src/message/repo/datastore/index.ts
src/module/dataset/metadata/repo/datastore/index.ts
src/module/dataset/proof/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/index.ts
src/module/matching/target/repo/datastore/index.ts
test/unittests/datastore/datasetmetadata.test.ts
test/unittests/datastore/datasetproof.test.ts
test/unittests/datastore/datasetrequirements.test.ts
test/unittests/datastore/matchingmetadata.test.ts
test/unittests/datastore/matchingtarget.test.ts
test/unittests/datastore/message.test.ts

feat: 🎸 upgrade datastore to 1.0.0

---

src/module/dataset/requirement/repo/datastore/model.ts
src/module/dataset/requirement/repo/evm/index.ts
src/module/dataset/requirement/types/index.ts
test/assertions/module/datasetsAssertion.ts
test/interfaces/assertions/module/IDatasetsAssertion.ts
test/unittests/datastore/datasetrequirements.test.ts
test/unittests/decode/datasetrequirement.test.ts

feat: 🎸 datastore for datasetsrequirement

---

src/module/matching/target/repo/datastore/model.ts
test/unittests/datastore/matchingtarget.test.ts

feat: 🎸 datastore for matchings target

---

src/module/matching/metadata/repo/datastore/model.ts
test/unittests/datastore/matchingmetadata.test.ts

feat: 🎸 datastore for matchingss metadata

---

src/core/carstore/repo/evm/index.ts
src/core/carstore/types/index.ts
test/assertions/core/carstoreAssertion.ts
test/assertions/module/matchingsAssertion.ts
test/interfaces/assertions/core/ICarstoreAssertion.ts
test/unittests/core/carstore.test.ts

feat: 🎸 CarReplica interface add matchingId property

---

src/module/dataset/proof/repo/datastore/index.ts
src/module/dataset/proof/repo/datastore/model.ts
test/unittests/datastore/datasetproof.test.ts

feat: 🎸 datastore for datasets proof

---

src/core/carstore/repo/datastore/index.ts
src/core/carstore/repo/datastore/model.ts
src/core/carstore/repo/evm/index.ts
src/core/carstore/types/index.ts
test/unittests/core/carstore.test.ts
test/unittests/datastore/carstore.test.ts

✅ Closes: #109, closes #110
close

feat: 🎸 Add car and carReplica datastore

---

src/index.ts

feat: 🎸 Add the exports for data types and datastore

---

README.md

docs: ✏️ Update readme comment

---

src/core/carstore/repo/datastore/model.ts
src/core/carstore/repo/evm/index.ts
src/core/carstore/types/index.ts

fix: 🐛 add carId to CarReplica

---

src/shared/converters/index.ts

feat: 🎸 tools to convert matching target to car replicas

---

src/module/dataset/requirement/repo/datastore/model.ts
src/module/dataset/requirement/repo/evm/index.ts
src/module/dataset/requirement/types/index.ts
src/shared/converters/index.ts
test/unittests/decode/datasetrequirement.test.ts

feat: 🎸 tools to convert DatasetRequirements

---

src/shared/converters/index.ts

feat: 🎸 convert datasetproofs to cars

---

src/index.ts
src/shared/converters/index.ts

feat: 🎸 add merge tool for matchingTarget

---

src/core/escrow/repo/evm/index.ts
src/module/dataset/metadata/repo/evm/index.ts
src/module/dataset/proof/repo/evm/index.ts

fix: 🐛 debug decodemessage faild

---

src/module/matching/metadata/repo/datastore/index.ts

fix: 🐛 Modify the database name for MatchingMetadata

---

src/index.ts
src/shared/converters/index.ts
src/shared/datastoreUtils/index.ts

✅ Closes: #150 #151
close: #151 
close

feat: 🎸 Encapsulation of the data storage utility

---

src/index.ts
src/module/matching/target/repo/datastore/model.ts
src/shared/datastoreUtils/index.ts

fix: 🐛 fix matching target model

---

test/assertions/core/escrowAssertion.ts
test/interfaces/assertions/core/IEscrowAssertion.ts
test/unittests/core/escrow.test.ts

test: 💍 Complete escrow withdraw unit test

---

src/message/repo/datastore/model/index.ts

fix: 🐛 Modify the params of the DataswapMessage to optional

---

src/module/dataset/requirement/repo/datastore/model.ts
src/module/dataset/requirement/repo/evm/index.ts
src/module/dataset/requirement/types/index.ts
src/module/matching/target/repo/datastore/model.ts
src/module/matching/target/repo/evm/index.ts
src/module/matching/target/types/index.ts
src/shared/arrayUtils/index.ts
src/shared/converters/index.ts
test/assertions/module/datasetsAssertion.ts
test/unittests/datastore/datasetrequirements.test.ts
test/unittests/datastore/matchingtarget.test.ts
test/unittests/decode/matchingtarget.test.ts

feat: 🎸 modifying bigint within complex type

---

src/core/roles/repo/evm/index.ts

fix: 🐛 Remove grantDataswapContractRole duplicate interface

---

test/assertions/core/escrowAssertion.ts
test/interfaces/assertions/core/IEscrowAssertion.ts
test/unittests/core/escrow.test.ts

test: 💍 Add escrow collateralRedeem test code

---

src/core/carstore/repo/datastore/model.ts

fix: 🐛 CarReplica primary key configuration issue

---

src/module/dataset/requirement/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/model.ts
src/module/dataset/requirement/types/index.ts
src/module/matching/metadata/repo/evm/index.ts
test/unittests/datastore/datasetrequirements.test.ts

feat: 🎸 extend datasetrequirement

---

src/core/carstore/repo/datastore/index.ts
src/core/carstore/repo/evm/index.ts
test/unittests/datastore/carstore.test.ts

feat: 🎸 add update function for carreplica datastore

---

src/module/dataset/metadata/repo/datastore/index.ts
src/module/dataset/metadata/repo/datastore/model.ts
src/module/dataset/metadata/repo/evm/index.ts
src/module/dataset/metadata/types/index.ts
src/shared/converters/index.ts
src/shared/datastoreUtils/index.ts
test/testkits/setup/generator.ts
test/unittests/datastore/datasetmetadata.test.ts

feat: 🎸 update status in dataset metadata

---

src/core/carstore/repo/datastore/index.ts
src/message/repo/datastore/index.ts
src/module/dataset/metadata/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/index.ts
src/module/matching/bids/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/index.ts
src/module/matching/target/repo/datastore/index.ts

fix: 🐛 bug of extend method of datastore

---

package-lock.json
package.json
src/core/carstore/repo/datastore/model.ts
src/core/carstore/repo/evm/index.ts
src/core/carstore/types/index.ts
src/shared/converters/index.ts
test/unittests/core/carstore.test.ts
test/unittests/datastore/carstore.test.ts

feat: 🎸 Add a "dataType","cid" field to Car model

---

src/core/carstore/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/index.ts
test/unittests/datastore/carstore.test.ts
test/unittests/datastore/datasetrequirements.test.ts

fix: 🐛 Debug for methods of datastore update

---

src/core/carstore/repo/datastore/index.ts
test/unittests/datastore/carstore.test.ts

fix: 🐛 rename updateReplicaState to updateReplica

---

src/index.ts

fix: 🐛 Export MatchingBidMongoDatastore class

---

package-lock.json
package.json

fix: 🐛 update filecoin version to 2.1.3

---

src/module/matching/metadata/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/model.ts

fix: 🐛 Modify the requirement in the MatchingMetadata model

---

src/core/carstore/repo/datastore/index.ts

When the Car model executes updateReplica, if there is no replica information on the blockchain, the replica information is directly removed from the car
✅ Closes: #217
close

fix: 🐛 invalid car replica info

---

src/module/dataset/metadata/repo/evm/index.ts
src/module/matching/metadata/repo/evm/index.ts
test/unittests/decode/datasetmetadata.test.ts
test/unittests/decode/matchingmetadata.test.ts
test/unittests/decode/sample.test.ts

fix: 🐛 initialize status of metadata

---

src/core/carstore/repo/datastore/index.ts
src/core/carstore/repo/datastore/model.ts
src/core/carstore/types/index.ts
src/shared/converters/index.ts
test/unittests/datastore/carstore.test.ts

fix: 🐛 remove bigint member of replicaInfos of car

---

src/module/dataset/requirement/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/model.ts
src/module/dataset/requirement/types/index.ts

fix: 🐛 remove bigint form matchings of requirement

---

src/module/dataset/proof/repo/datastore/model.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/dataset/proof/types/index.ts
test/unittests/datastore/datasetproof.test.ts
test/unittests/decode/datasetproof.test.ts

feat: 🎸 Dataset proof add valid params

---

src/module/dataset/proof/repo/datastore/index.ts
src/module/dataset/proof/repo/datastore/model.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/dataset/proof/types/index.ts
test/unittests/datastore/datasetproof.test.ts
test/unittests/decode/datasetproof.test.ts

feat: 🎸 Write the dataset's size into the dataset proof

---

src/core/carstore/repo/datastore/index.ts
src/core/carstore/repo/datastore/model.ts
src/core/carstore/types/index.ts
src/shared/converters/index.ts
test/unittests/datastore/carstore.test.ts

fix: 🐛 Add the index field to CarReplica

---

src/core/carstore/repo/datastore/index.ts

fix: 🐛 matchingId in replicaInfos of the car has not update

---

src/core/carstore/repo/datastore/index.ts
src/module/dataset/proof/repo/datastore/index.ts
src/module/dataset/requirement/repo/datastore/index.ts

fix: 🐛 invalid query for update and find

---

src/module/matching/bids/repo/datastore/index.ts
src/module/matching/bids/repo/datastore/model.ts
src/module/matching/bids/repo/evm/index.ts
src/module/matching/bids/types/index.ts
test/unittests/datastore/matchingbid.test.ts
test/unittests/decode/matchingbids.test.ts

fix: 🐛 add height to matchingBid

---

src/core/carstore/repo/datastore/index.ts

fix: 🐛 update matchingid in replicainfos

---

src/module/matching/metadata/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/model.ts
src/module/matching/metadata/types/index.ts
test/unittests/datastore/matchingmetadata.test.ts

fix: 🐛 add winner to matchingmetadata

---

src/index.ts
src/module/dataset/challenge/repo/datastore/index.ts
src/module/dataset/challenge/repo/datastore/model.ts
src/module/dataset/challenge/repo/evm/index.ts
src/module/dataset/challenge/types/index.ts
src/module/matching/metadata/repo/datastore/index.ts
test/assertions/module/datasetsAssertion.ts
test/unittests/decode/datasetchallenge.test.ts

feat: 🎸 add model of datasetchallenge

---

src/index.ts

fix: 🐛 export BidSelectionRule

---

src/shared/evmInstances/config.ts

feat: 🎸 update contract address to version v0.4.0

---

src/core/filplus/repo/evm/index.ts
src/core/finance/types/index.ts
src/shared/types/financeType.ts
test/assertions/core/filplusAssertion.ts
test/interfaces/assertions/core/IFilplusAssertion.ts
test/unittests/core/filplus.test.ts

feat: 🎸 Enhance the functionality of Filplus related to EVM

---

src/core/community/repo/datastore/index.ts
src/core/community/repo/datastore/model.ts
src/core/community/types/index.ts
test/unittests/datastore/community.test.ts

feat: 🎸 Design of community members data statistics model

---

src/core/finance/repo/evm/index.ts
src/core/finance/types/index.ts
src/index.ts
src/shared/evmInstances/evm.ts
test/assertions/core/financeAssertion.ts
test/interfaces/assertions/core/IFinanceAssertion.ts

feat: 🎸 Enhance the functionality of Finance statistics

---

src/module/dataset/metadata/repo/datastore/index.ts
src/module/dataset/metadata/repo/datastore/model.ts
src/module/dataset/metadata/types/index.ts
src/module/matching/metadata/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/model.ts
src/module/matching/metadata/types/index.ts

feat: 🎸 Design of the fund unit price statistics data model

---

src/core/statistics/repo/datastore/index.ts
src/core/statistics/repo/datastore/model.ts
src/index.ts
src/shared/types/statisticsType.ts
test/unittests/datastore/statistics.test.ts

feat: 🎸 Design of storage-related data statistics model

---

src/core/statistics/repo/datastore/index.ts
src/core/statistics/repo/datastore/model.ts
src/index.ts
src/module/dataset/metadata/repo/evm/index.ts
src/module/matching/metadata/repo/evm/index.ts
src/module/storages/repo/evm/index.ts
src/shared/types/statisticsType.ts
test/unittests/datastore/statistics.test.ts

feat: 🎸 export storage-related data statistics interfaces

---

src/core/statistics/repo/datastore/model.ts
src/shared/types/statisticsType.ts
test/assertions/module/datasetsAssertion.ts
test/assertions/module/matchingsAssertion.ts
test/assertions/module/storagesAssertion.ts
test/interfaces/assertions/module/IDatasetsAssertion.ts
test/interfaces/assertions/module/IMatchingsAssertion.ts
test/interfaces/assertions/module/IStoragesAssertion.ts
test/unittests/datastore/statistics.test.ts

feat: 🎸 basic statistics test

---

src/core/carstore/repo/datastore/index.ts
src/index.ts
src/module/dataset/metadata/repo/datastore/index.ts
src/module/dataset/metadata/repo/datastore/model.ts
src/module/dataset/metadata/repo/evm/index.ts
src/module/dataset/metadata/types/index.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/dataset/proof/types/index.ts
src/shared/converters/index.ts
test/unittests/decode/datasetmetadata.test.ts
test/unittests/decode/sample.test.ts

fix: 🐛 datasets related types

---

src/core/community/repo/datastore/index.ts
src/module/dataset/proof/repo/datastore/model.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/dataset/proof/types/index.ts

fix: 🐛 Add member missing parameter

---

src/module/storages/repo/evm/index.ts

fix: 🐛 registDataswapDatacap decode error

---

src/module/dataset/metadata/repo/datastore/index.ts
src/module/matching/metadata/repo/datastore/index.ts
test/unittests/datastore/matchingmetadata.test.ts

fix: 🐛 fix updata function of datastore

---

src/module/matching/metadata/repo/datastore/index.ts

fix: 🐛 error_2:Error: bids is none

---

src/module/matching/bids/repo/datastore/index.ts
src/shared/converters/index.ts
test/unittests/datastore/matchingbid.test.ts

fix: 🐛 error_1:Error: cant find the bidder on chain

---

package-lock.json
package.json

feat: 🎸 update abi version to 0.6.0

---

src/module/dataset/challenge/repo/evm/index.ts
src/module/dataset/metadata/repo/evm/index.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/matching/bids/repo/datastore/index.ts
src/module/matching/bids/repo/evm/index.ts
src/module/matching/metadata/repo/evm/index.ts
src/shared/converters/index.ts
test/unittests/datastore/matchingbid.test.ts
test/unittests/decode/datasetchallenge.test.ts
test/unittests/decode/datasetmetadata.test.ts
test/unittests/decode/datasetproof.test.ts
test/unittests/decode/matchingbids.test.ts
test/unittests/decode/matchingmetadata.test.ts
test/unittests/decode/sample.test.ts

fix: 🐛 Error(payer account does not exist)

---

src/shared/evmInstances/config.ts

feat: 🎸 update evm instance contracts addresses

---

package-lock.json
package.json
src/module/dataset/requirement/repo/datastore/index.ts
test/assertions/module/datasetsAssertion.ts

fix: 🐛 fix:error:matching already exist

---

package-lock.json
package.json

fix: 🐛 update abi version to 0.7.0

---

src/shared/evmInstances/config.ts

fix: 🐛 update contract addresses in calibnet

---

package-lock.json
package.json
src/shared/evmInstances/evm.ts
test/unittests/module/datasets.test.ts
test/unittests/module/matchings.test.ts

feat: 🎸 update abi version to 0.8.0

---

package-lock.json
package.json

fix: 🐛 update filecoin version to 2.2.1

---

.github/workflows/test.yml
src/core/carstore/repo/evm/index.ts
src/core/filplus/repo/evm/index.ts
src/core/finance/repo/evm/index.ts
src/core/roles/repo/evm/index.ts
src/module/dataset/challenge/repo/evm/index.ts
src/module/storages/repo/evm/index.ts
src/shared/types/evmEngineType.ts
src/shared/types/rolesType.ts
test/assertions/module/datasetsAssertion.ts
test/helpers/module/matchingsHelper.ts
test/interfaces/assertions/module/IDatasetsAssertion.ts
test/testkits/module/datasets/DatasetsChallengeTestKit.ts
test/testkits/module/datasets/DatasetsMetadataTestKit.ts
test/testkits/module/matchings/MatchingsBidsTestKit.ts
test/unittests/module/datasets.test.ts
test/unittests/module/matchings.test.ts

fix: 🐛 Supporting dataset auditor election functionality

---

src/shared/evmInstances/config.ts

fix: 🐛 update calibnet contracts address

---

package-lock.json
package.json
src/core/filplus/repo/evm/index.ts
src/module/dataset/challenge/repo/evm/index.ts
src/shared/evmInstances/config.ts
test/assertions/core/filplusAssertion.ts
test/assertions/module/datasetsAssertion.ts
test/interfaces/assertions/module/IDatasetsAssertion.ts
test/testkits/module/datasets/DatasetsChallengeTestKit.ts
test/unittests/core/filplus.test.ts
test/unittests/decode/filplus.test.ts

Fix/update abi version to 0.9.0

---

package-lock.json
package.json

fix: 🐛 update filecoin version to 2.3.0

---

src/module/matching/metadata/repo/datastore/index.ts

fix: 🐛 change winner to ethaddress in matchingmetadata

---

src/core/statistics/repo/datastore/index.ts

fix: 🐛 update statistics from events

---

package-lock.json
package.json
src/core/filplus/repo/evm/index.ts
src/core/statistics/repo/datastore/index.ts
src/index.ts
src/module/dataset/proof/repo/evm/index.ts
test/testkits/module/datasets/DatasetsChallengeTestKit.ts
test/unittests/datastore/statistics.test.ts

fix: 🐛 update abi version to 0.9.1

---

package-lock.json
package.json
src/core/statistics/repo/datastore/index.ts
src/shared/types/evmEngineType.ts
test/assertions/module/datasetsAssertion.ts
test/interfaces/assertions/module/IDatasetsAssertion.ts
test/testkits/module/datasets/DatasetsChallengeTestKit.ts

fix: 🐛 update abi version to 0.9.2

---

src/core/filplus/repo/evm/index.ts
src/core/finance/repo/evm/index.ts
src/core/roles/repo/evm/index.ts
src/module/dataset/challenge/repo/evm/index.ts
src/module/dataset/metadata/repo/evm/index.ts
src/module/dataset/proof/repo/evm/index.ts
src/module/dataset/requirement/repo/evm/index.ts
src/module/matching/bids/repo/evm/index.ts
src/module/matching/metadata/repo/evm/index.ts
src/module/matching/target/repo/evm/index.ts
src/module/storages/repo/evm/index.ts

fix: 🐛 add upgradeTo to decodeMessage

---

src/core/filplus/repo/evm/index.ts

fix: 🐛 The issue with decoding the parameters of the Filplus

---

src/module/storages/repo/evm/index.ts

fix: 🐛 getMatchingStorageOverview bug

---

src/module/dataset/requirement/repo/datastore/index.ts

fix: 🐛 getMatchings of DatasetRequirementMongoDatastore
